name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gh-pages  # Nombre del artefacto
          path: static    # Ruta al directorio que deseas subir como artefacto

  deploy:
    needs: build

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: gh-pages  # Nombre del artefacto

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.TOKEN_DEPLOY }}  # Utiliza tu nuevo token de acceso personal aquí
