name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request :
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy :
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build
      - name : Upload Artifact
        uses : actions/upload-artifact@v3
        with:
          name : production-files
          path : ./dist


  deploy:
    # Add a dependency to the build job
    needs: build
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_DEPLOY }}
          publish_dir: ./dist
