name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # Cambia "gh-pages" al nombre de tu rama de despliegue si es diferente
          folder: static    # Cambia "build" al directorio de tu aplicación si es diferente
